version: 2
updates:
    - package-ecosystem: elm
      directory: ./
      schedule:
          interval: daily
      allow:
          - dependency-name: 'ren-lang/compiler'
      assignees:
          - 'hayleigh-dot-dev'
          - 'aslilac'
